[package]
name = "pms5003"
version = "0.1.0"
authors = ["Matthias Wolf <m@sushinara.net>"]
description = "A device driver for the Plantower PMS5003 particulate matter sensor"
repository = "https://github.com/matz-e/pms5003.rs"
edition = "2018"

[dependencies]
embedded-hal = "0.2.3"
nb = "0.1.3"
